# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Attr(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, attr_id: str=None, attr_us_name: str=None, attr_kr_name: str=None):  # noqa: E501
        """Attr - a model defined in Swagger

        :param attr_id: The attr_id of this Attr.  # noqa: E501
        :type attr_id: str
        :param attr_us_name: The attr_us_name of this Attr.  # noqa: E501
        :type attr_us_name: str
        :param attr_kr_name: The attr_kr_name of this Attr.  # noqa: E501
        :type attr_kr_name: str
        """
        self.swagger_types = {
            'attr_id': str,
            'attr_us_name': str,
            'attr_kr_name': str
        }

        self.attribute_map = {
            'attr_id': 'attr_id',
            'attr_us_name': 'attr_us_name',
            'attr_kr_name': 'attr_kr_name'
        }

        self._attr_id = attr_id
        self._attr_us_name = attr_us_name
        self._attr_kr_name = attr_kr_name

    @classmethod
    def from_dict(cls, dikt) -> 'Attr':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attr of this Attr.  # noqa: E501
        :rtype: Attr
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attr_id(self) -> str:
        """Gets the attr_id of this Attr.


        :return: The attr_id of this Attr.
        :rtype: str
        """
        return self._attr_id

    @attr_id.setter
    def attr_id(self, attr_id: str):
        """Sets the attr_id of this Attr.


        :param attr_id: The attr_id of this Attr.
        :type attr_id: str
        """

        self._attr_id = attr_id

    @property
    def attr_us_name(self) -> str:
        """Gets the attr_us_name of this Attr.


        :return: The attr_us_name of this Attr.
        :rtype: str
        """
        return self._attr_us_name

    @attr_us_name.setter
    def attr_us_name(self, attr_us_name: str):
        """Sets the attr_us_name of this Attr.


        :param attr_us_name: The attr_us_name of this Attr.
        :type attr_us_name: str
        """

        self._attr_us_name = attr_us_name

    @property
    def attr_kr_name(self) -> str:
        """Gets the attr_kr_name of this Attr.


        :return: The attr_kr_name of this Attr.
        :rtype: str
        """
        return self._attr_kr_name

    @attr_kr_name.setter
    def attr_kr_name(self, attr_kr_name: str):
        """Sets the attr_kr_name of this Attr.


        :param attr_kr_name: The attr_kr_name of this Attr.
        :type attr_kr_name: str
        """

        self._attr_kr_name = attr_kr_name
