# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Attr(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, attr_code: str=None, value: str=None):  # noqa: E501
        """Attr - a model defined in Swagger

        :param attr_code: The attr_code of this Attr.  # noqa: E501
        :type attr_code: str
        :param value: The value of this Attr.  # noqa: E501
        :type value: str
        """
        self.swagger_types = {
            'attr_code': str,
            'value': str
        }

        self.attribute_map = {
            'attr_code': 'attr_code',
            'value': 'value'
        }

        self._attr_code = attr_code
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Attr':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Attr of this Attr.  # noqa: E501
        :rtype: Attr
        """
        return util.deserialize_model(dikt, cls)

    @property
    def attr_code(self) -> str:
        """Gets the attr_code of this Attr.


        :return: The attr_code of this Attr.
        :rtype: str
        """
        return self._attr_code

    @attr_code.setter
    def attr_code(self, attr_code: str):
        """Sets the attr_code of this Attr.


        :param attr_code: The attr_code of this Attr.
        :type attr_code: str
        """

        self._attr_code = attr_code

    @property
    def value(self) -> str:
        """Gets the value of this Attr.


        :return: The value of this Attr.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Attr.


        :param value: The value of this Attr.
        :type value: str
        """

        self._value = value
