# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FeedSubmissionInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, feed_submission_id: str=None, feed_processing_status: str=None, feed_type: str=None):  # noqa: E501
        """FeedSubmissionInfo - a model defined in Swagger

        :param feed_submission_id: The feed_submission_id of this FeedSubmissionInfo.  # noqa: E501
        :type feed_submission_id: str
        :param feed_processing_status: The feed_processing_status of this FeedSubmissionInfo.  # noqa: E501
        :type feed_processing_status: str
        :param feed_type: The feed_type of this FeedSubmissionInfo.  # noqa: E501
        :type feed_type: str
        """
        self.swagger_types = {
            'feed_submission_id': str,
            'feed_processing_status': str,
            'feed_type': str
        }

        self.attribute_map = {
            'feed_submission_id': 'feed_submission_id',
            'feed_processing_status': 'feed_processing_status',
            'feed_type': 'feed_type'
        }

        self._feed_submission_id = feed_submission_id
        self._feed_processing_status = feed_processing_status
        self._feed_type = feed_type

    @classmethod
    def from_dict(cls, dikt) -> 'FeedSubmissionInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedSubmissionInfo of this FeedSubmissionInfo.  # noqa: E501
        :rtype: FeedSubmissionInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_submission_id(self) -> str:
        """Gets the feed_submission_id of this FeedSubmissionInfo.


        :return: The feed_submission_id of this FeedSubmissionInfo.
        :rtype: str
        """
        return self._feed_submission_id

    @feed_submission_id.setter
    def feed_submission_id(self, feed_submission_id: str):
        """Sets the feed_submission_id of this FeedSubmissionInfo.


        :param feed_submission_id: The feed_submission_id of this FeedSubmissionInfo.
        :type feed_submission_id: str
        """

        self._feed_submission_id = feed_submission_id

    @property
    def feed_processing_status(self) -> str:
        """Gets the feed_processing_status of this FeedSubmissionInfo.


        :return: The feed_processing_status of this FeedSubmissionInfo.
        :rtype: str
        """
        return self._feed_processing_status

    @feed_processing_status.setter
    def feed_processing_status(self, feed_processing_status: str):
        """Sets the feed_processing_status of this FeedSubmissionInfo.


        :param feed_processing_status: The feed_processing_status of this FeedSubmissionInfo.
        :type feed_processing_status: str
        """

        self._feed_processing_status = feed_processing_status

    @property
    def feed_type(self) -> str:
        """Gets the feed_type of this FeedSubmissionInfo.


        :return: The feed_type of this FeedSubmissionInfo.
        :rtype: str
        """
        return self._feed_type

    @feed_type.setter
    def feed_type(self, feed_type: str):
        """Sets the feed_type of this FeedSubmissionInfo.


        :param feed_type: The feed_type of this FeedSubmissionInfo.
        :type feed_type: str
        """

        self._feed_type = feed_type
