# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.feed_submission_info import FeedSubmissionInfo  # noqa: F401,E501
from swagger_server import util


class GetMwsFeedsSubmissionsResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, feed_submission_info: List[FeedSubmissionInfo]=None, has_next: str=None, next_token: str=None):  # noqa: E501
        """GetMwsFeedsSubmissionsResponseData - a model defined in Swagger

        :param feed_submission_info: The feed_submission_info of this GetMwsFeedsSubmissionsResponseData.  # noqa: E501
        :type feed_submission_info: List[FeedSubmissionInfo]
        :param has_next: The has_next of this GetMwsFeedsSubmissionsResponseData.  # noqa: E501
        :type has_next: str
        :param next_token: The next_token of this GetMwsFeedsSubmissionsResponseData.  # noqa: E501
        :type next_token: str
        """
        self.swagger_types = {
            'feed_submission_info': List[FeedSubmissionInfo],
            'has_next': str,
            'next_token': str
        }

        self.attribute_map = {
            'feed_submission_info': 'feed_submission_info',
            'has_next': 'has_next',
            'next_token': 'next_token'
        }

        self._feed_submission_info = feed_submission_info
        self._has_next = has_next
        self._next_token = next_token

    @classmethod
    def from_dict(cls, dikt) -> 'GetMwsFeedsSubmissionsResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetMwsFeedsSubmissionsResponse_data of this GetMwsFeedsSubmissionsResponseData.  # noqa: E501
        :rtype: GetMwsFeedsSubmissionsResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_submission_info(self) -> List[FeedSubmissionInfo]:
        """Gets the feed_submission_info of this GetMwsFeedsSubmissionsResponseData.


        :return: The feed_submission_info of this GetMwsFeedsSubmissionsResponseData.
        :rtype: List[FeedSubmissionInfo]
        """
        return self._feed_submission_info

    @feed_submission_info.setter
    def feed_submission_info(self, feed_submission_info: List[FeedSubmissionInfo]):
        """Sets the feed_submission_info of this GetMwsFeedsSubmissionsResponseData.


        :param feed_submission_info: The feed_submission_info of this GetMwsFeedsSubmissionsResponseData.
        :type feed_submission_info: List[FeedSubmissionInfo]
        """

        self._feed_submission_info = feed_submission_info

    @property
    def has_next(self) -> str:
        """Gets the has_next of this GetMwsFeedsSubmissionsResponseData.


        :return: The has_next of this GetMwsFeedsSubmissionsResponseData.
        :rtype: str
        """
        return self._has_next

    @has_next.setter
    def has_next(self, has_next: str):
        """Sets the has_next of this GetMwsFeedsSubmissionsResponseData.


        :param has_next: The has_next of this GetMwsFeedsSubmissionsResponseData.
        :type has_next: str
        """

        self._has_next = has_next

    @property
    def next_token(self) -> str:
        """Gets the next_token of this GetMwsFeedsSubmissionsResponseData.


        :return: The next_token of this GetMwsFeedsSubmissionsResponseData.
        :rtype: str
        """
        return self._next_token

    @next_token.setter
    def next_token(self, next_token: str):
        """Sets the next_token of this GetMwsFeedsSubmissionsResponseData.


        :param next_token: The next_token of this GetMwsFeedsSubmissionsResponseData.
        :type next_token: str
        """

        self._next_token = next_token
