# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_dictionary_words_filtered_response_data_words import GetDictionaryWordsFilteredResponseDataWords  # noqa: F401,E501
from swagger_server import util


class GetDictionaryWordsFilteredResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, words: List[GetDictionaryWordsFilteredResponseDataWords]=None):  # noqa: E501
        """GetDictionaryWordsFilteredResponseData - a model defined in Swagger

        :param words: The words of this GetDictionaryWordsFilteredResponseData.  # noqa: E501
        :type words: List[GetDictionaryWordsFilteredResponseDataWords]
        """
        self.swagger_types = {
            'words': List[GetDictionaryWordsFilteredResponseDataWords]
        }

        self.attribute_map = {
            'words': 'words'
        }

        self._words = words

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryWordsFilteredResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryWordsFilteredResponse_data of this GetDictionaryWordsFilteredResponseData.  # noqa: E501
        :rtype: GetDictionaryWordsFilteredResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def words(self) -> List[GetDictionaryWordsFilteredResponseDataWords]:
        """Gets the words of this GetDictionaryWordsFilteredResponseData.


        :return: The words of this GetDictionaryWordsFilteredResponseData.
        :rtype: List[GetDictionaryWordsFilteredResponseDataWords]
        """
        return self._words

    @words.setter
    def words(self, words: List[GetDictionaryWordsFilteredResponseDataWords]):
        """Sets the words of this GetDictionaryWordsFilteredResponseData.


        :param words: The words of this GetDictionaryWordsFilteredResponseData.
        :type words: List[GetDictionaryWordsFilteredResponseDataWords]
        """

        self._words = words
