# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetProductsBrowseNodeValidValueResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, valid_value: str=None):  # noqa: E501
        """GetProductsBrowseNodeValidValueResponseData - a model defined in Swagger

        :param valid_value: The valid_value of this GetProductsBrowseNodeValidValueResponseData.  # noqa: E501
        :type valid_value: str
        """
        self.swagger_types = {
            'valid_value': str
        }

        self.attribute_map = {
            'valid_value': 'valid_value'
        }

        self._valid_value = valid_value

    @classmethod
    def from_dict(cls, dikt) -> 'GetProductsBrowseNodeValidValueResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProductsBrowseNodeValidValueResponse_data of this GetProductsBrowseNodeValidValueResponseData.  # noqa: E501
        :rtype: GetProductsBrowseNodeValidValueResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def valid_value(self) -> str:
        """Gets the valid_value of this GetProductsBrowseNodeValidValueResponseData.


        :return: The valid_value of this GetProductsBrowseNodeValidValueResponseData.
        :rtype: str
        """
        return self._valid_value

    @valid_value.setter
    def valid_value(self, valid_value: str):
        """Sets the valid_value of this GetProductsBrowseNodeValidValueResponseData.


        :param valid_value: The valid_value of this GetProductsBrowseNodeValidValueResponseData.
        :type valid_value: str
        """

        self._valid_value = valid_value
