# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetDictionaryProductsAttrsSubAttrsWordsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: bool=None):  # noqa: E501
        """GetDictionaryProductsAttrsSubAttrsWordsResponse - a model defined in Swagger

        :param message: The message of this GetDictionaryProductsAttrsSubAttrsWordsResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetDictionaryProductsAttrsSubAttrsWordsResponse.  # noqa: E501
        :type data: bool
        """
        self.swagger_types = {
            'message': str,
            'data': bool
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryProductsAttrsSubAttrsWordsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryProductsAttrsSubAttrsWordsResponse of this GetDictionaryProductsAttrsSubAttrsWordsResponse.  # noqa: E501
        :rtype: GetDictionaryProductsAttrsSubAttrsWordsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetDictionaryProductsAttrsSubAttrsWordsResponse.


        :return: The message of this GetDictionaryProductsAttrsSubAttrsWordsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetDictionaryProductsAttrsSubAttrsWordsResponse.


        :param message: The message of this GetDictionaryProductsAttrsSubAttrsWordsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> bool:
        """Gets the data of this GetDictionaryProductsAttrsSubAttrsWordsResponse.


        :return: The data of this GetDictionaryProductsAttrsSubAttrsWordsResponse.
        :rtype: bool
        """
        return self._data

    @data.setter
    def data(self, data: bool):
        """Sets the data of this GetDictionaryProductsAttrsSubAttrsWordsResponse.


        :param data: The data of this GetDictionaryProductsAttrsSubAttrsWordsResponse.
        :type data: bool
        """

        self._data = data
