# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetToolTitlesResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, titles: List[str]=None):  # noqa: E501
        """GetToolTitlesResponseData - a model defined in Swagger

        :param titles: The titles of this GetToolTitlesResponseData.  # noqa: E501
        :type titles: List[str]
        """
        self.swagger_types = {
            'titles': List[str]
        }

        self.attribute_map = {
            'titles': 'titles'
        }

        self._titles = titles

    @classmethod
    def from_dict(cls, dikt) -> 'GetToolTitlesResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetToolTitlesResponse_data of this GetToolTitlesResponseData.  # noqa: E501
        :rtype: GetToolTitlesResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def titles(self) -> List[str]:
        """Gets the titles of this GetToolTitlesResponseData.


        :return: The titles of this GetToolTitlesResponseData.
        :rtype: List[str]
        """
        return self._titles

    @titles.setter
    def titles(self, titles: List[str]):
        """Sets the titles of this GetToolTitlesResponseData.


        :param titles: The titles of this GetToolTitlesResponseData.
        :type titles: List[str]
        """

        self._titles = titles
