# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.attr import Attr  # noqa: F401,E501
from swagger_server import util


class GetDictionaryProductsAttrsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: Attr=None):  # noqa: E501
        """GetDictionaryProductsAttrsResponse - a model defined in Swagger

        :param message: The message of this GetDictionaryProductsAttrsResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetDictionaryProductsAttrsResponse.  # noqa: E501
        :type data: Attr
        """
        self.swagger_types = {
            'message': str,
            'data': Attr
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryProductsAttrsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryProductsAttrsResponse of this GetDictionaryProductsAttrsResponse.  # noqa: E501
        :rtype: GetDictionaryProductsAttrsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetDictionaryProductsAttrsResponse.


        :return: The message of this GetDictionaryProductsAttrsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetDictionaryProductsAttrsResponse.


        :param message: The message of this GetDictionaryProductsAttrsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> Attr:
        """Gets the data of this GetDictionaryProductsAttrsResponse.


        :return: The data of this GetDictionaryProductsAttrsResponse.
        :rtype: Attr
        """
        return self._data

    @data.setter
    def data(self, data: Attr):
        """Sets the data of this GetDictionaryProductsAttrsResponse.


        :param data: The data of this GetDictionaryProductsAttrsResponse.
        :type data: Attr
        """

        self._data = data
