# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_mws_feeds_submissions_response_data import GetMwsFeedsSubmissionsResponseData  # noqa: F401,E501
from swagger_server import util


class GetMwsFeedsSubmissionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetMwsFeedsSubmissionsResponseData=None):  # noqa: E501
        """GetMwsFeedsSubmissionsResponse - a model defined in Swagger

        :param message: The message of this GetMwsFeedsSubmissionsResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetMwsFeedsSubmissionsResponse.  # noqa: E501
        :type data: GetMwsFeedsSubmissionsResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetMwsFeedsSubmissionsResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetMwsFeedsSubmissionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetMwsFeedsSubmissionsResponse of this GetMwsFeedsSubmissionsResponse.  # noqa: E501
        :rtype: GetMwsFeedsSubmissionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetMwsFeedsSubmissionsResponse.


        :return: The message of this GetMwsFeedsSubmissionsResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetMwsFeedsSubmissionsResponse.


        :param message: The message of this GetMwsFeedsSubmissionsResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetMwsFeedsSubmissionsResponseData:
        """Gets the data of this GetMwsFeedsSubmissionsResponse.


        :return: The data of this GetMwsFeedsSubmissionsResponse.
        :rtype: GetMwsFeedsSubmissionsResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetMwsFeedsSubmissionsResponseData):
        """Sets the data of this GetMwsFeedsSubmissionsResponse.


        :param data: The data of this GetMwsFeedsSubmissionsResponse.
        :type data: GetMwsFeedsSubmissionsResponseData
        """

        self._data = data
