# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_dictionary_words_filtered_response_data import GetDictionaryWordsFilteredResponseData  # noqa: F401,E501
from swagger_server import util


class GetDictionaryWordsFilteredResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetDictionaryWordsFilteredResponseData=None):  # noqa: E501
        """GetDictionaryWordsFilteredResponse - a model defined in Swagger

        :param message: The message of this GetDictionaryWordsFilteredResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetDictionaryWordsFilteredResponse.  # noqa: E501
        :type data: GetDictionaryWordsFilteredResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetDictionaryWordsFilteredResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryWordsFilteredResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryWordsFilteredResponse of this GetDictionaryWordsFilteredResponse.  # noqa: E501
        :rtype: GetDictionaryWordsFilteredResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetDictionaryWordsFilteredResponse.


        :return: The message of this GetDictionaryWordsFilteredResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetDictionaryWordsFilteredResponse.


        :param message: The message of this GetDictionaryWordsFilteredResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetDictionaryWordsFilteredResponseData:
        """Gets the data of this GetDictionaryWordsFilteredResponse.


        :return: The data of this GetDictionaryWordsFilteredResponse.
        :rtype: GetDictionaryWordsFilteredResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetDictionaryWordsFilteredResponseData):
        """Sets the data of this GetDictionaryWordsFilteredResponse.


        :param data: The data of this GetDictionaryWordsFilteredResponse.
        :type data: GetDictionaryWordsFilteredResponseData
        """

        self._data = data
