# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetDictionaryWordsFilteredResponseDataWords(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, text: str=None, count: str=None):  # noqa: E501
        """GetDictionaryWordsFilteredResponseDataWords - a model defined in Swagger

        :param text: The text of this GetDictionaryWordsFilteredResponseDataWords.  # noqa: E501
        :type text: str
        :param count: The count of this GetDictionaryWordsFilteredResponseDataWords.  # noqa: E501
        :type count: str
        """
        self.swagger_types = {
            'text': str,
            'count': str
        }

        self.attribute_map = {
            'text': 'text',
            'count': 'count'
        }

        self._text = text
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryWordsFilteredResponseDataWords':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryWordsFilteredResponse_data_words of this GetDictionaryWordsFilteredResponseDataWords.  # noqa: E501
        :rtype: GetDictionaryWordsFilteredResponseDataWords
        """
        return util.deserialize_model(dikt, cls)

    @property
    def text(self) -> str:
        """Gets the text of this GetDictionaryWordsFilteredResponseDataWords.


        :return: The text of this GetDictionaryWordsFilteredResponseDataWords.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this GetDictionaryWordsFilteredResponseDataWords.


        :param text: The text of this GetDictionaryWordsFilteredResponseDataWords.
        :type text: str
        """

        self._text = text

    @property
    def count(self) -> str:
        """Gets the count of this GetDictionaryWordsFilteredResponseDataWords.


        :return: The count of this GetDictionaryWordsFilteredResponseDataWords.
        :rtype: str
        """
        return self._count

    @count.setter
    def count(self, count: str):
        """Sets the count of this GetDictionaryWordsFilteredResponseDataWords.


        :param count: The count of this GetDictionaryWordsFilteredResponseDataWords.
        :type count: str
        """

        self._count = count
