# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_advertising_browse_nodes_response_data import GetAdvertisingBrowseNodesResponseData  # noqa: F401,E501
from swagger_server import util


class GetAdvertisingBrowseNodesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetAdvertisingBrowseNodesResponseData=None):  # noqa: E501
        """GetAdvertisingBrowseNodesResponse - a model defined in Swagger

        :param message: The message of this GetAdvertisingBrowseNodesResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetAdvertisingBrowseNodesResponse.  # noqa: E501
        :type data: GetAdvertisingBrowseNodesResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetAdvertisingBrowseNodesResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAdvertisingBrowseNodesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAdvertisingBrowseNodesResponse of this GetAdvertisingBrowseNodesResponse.  # noqa: E501
        :rtype: GetAdvertisingBrowseNodesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetAdvertisingBrowseNodesResponse.


        :return: The message of this GetAdvertisingBrowseNodesResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetAdvertisingBrowseNodesResponse.


        :param message: The message of this GetAdvertisingBrowseNodesResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetAdvertisingBrowseNodesResponseData:
        """Gets the data of this GetAdvertisingBrowseNodesResponse.


        :return: The data of this GetAdvertisingBrowseNodesResponse.
        :rtype: GetAdvertisingBrowseNodesResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetAdvertisingBrowseNodesResponseData):
        """Sets the data of this GetAdvertisingBrowseNodesResponse.


        :param data: The data of this GetAdvertisingBrowseNodesResponse.
        :type data: GetAdvertisingBrowseNodesResponseData
        """

        self._data = data
