# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_advertising_browse_nodes_top_sellers_response_data import GetAdvertisingBrowseNodesTopSellersResponseData  # noqa: F401,E501
from swagger_server import util


class GetAdvertisingBrowseNodesTopSellersResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetAdvertisingBrowseNodesTopSellersResponseData=None):  # noqa: E501
        """GetAdvertisingBrowseNodesTopSellersResponse - a model defined in Swagger

        :param message: The message of this GetAdvertisingBrowseNodesTopSellersResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetAdvertisingBrowseNodesTopSellersResponse.  # noqa: E501
        :type data: GetAdvertisingBrowseNodesTopSellersResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetAdvertisingBrowseNodesTopSellersResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetAdvertisingBrowseNodesTopSellersResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetAdvertisingBrowseNodesTopSellersResponse of this GetAdvertisingBrowseNodesTopSellersResponse.  # noqa: E501
        :rtype: GetAdvertisingBrowseNodesTopSellersResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetAdvertisingBrowseNodesTopSellersResponse.


        :return: The message of this GetAdvertisingBrowseNodesTopSellersResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetAdvertisingBrowseNodesTopSellersResponse.


        :param message: The message of this GetAdvertisingBrowseNodesTopSellersResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetAdvertisingBrowseNodesTopSellersResponseData:
        """Gets the data of this GetAdvertisingBrowseNodesTopSellersResponse.


        :return: The data of this GetAdvertisingBrowseNodesTopSellersResponse.
        :rtype: GetAdvertisingBrowseNodesTopSellersResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetAdvertisingBrowseNodesTopSellersResponseData):
        """Sets the data of this GetAdvertisingBrowseNodesTopSellersResponse.


        :param data: The data of this GetAdvertisingBrowseNodesTopSellersResponse.
        :type data: GetAdvertisingBrowseNodesTopSellersResponseData
        """

        self._data = data
