# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GetDictionaryWordsResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, words: List[str]=None):  # noqa: E501
        """GetDictionaryWordsResponseData - a model defined in Swagger

        :param words: The words of this GetDictionaryWordsResponseData.  # noqa: E501
        :type words: List[str]
        """
        self.swagger_types = {
            'words': List[str]
        }

        self.attribute_map = {
            'words': 'words'
        }

        self._words = words

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryWordsResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryWordsResponse_data of this GetDictionaryWordsResponseData.  # noqa: E501
        :rtype: GetDictionaryWordsResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def words(self) -> List[str]:
        """Gets the words of this GetDictionaryWordsResponseData.


        :return: The words of this GetDictionaryWordsResponseData.
        :rtype: List[str]
        """
        return self._words

    @words.setter
    def words(self, words: List[str]):
        """Sets the words of this GetDictionaryWordsResponseData.


        :param words: The words of this GetDictionaryWordsResponseData.
        :type words: List[str]
        """

        self._words = words
