# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_products_browse_node_attributes_response_data import GetProductsBrowseNodeAttributesResponseData  # noqa: F401,E501
from swagger_server import util


class GetProductsBrowseNodeAttributesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: List[GetProductsBrowseNodeAttributesResponseData]=None):  # noqa: E501
        """GetProductsBrowseNodeAttributesResponse - a model defined in Swagger

        :param message: The message of this GetProductsBrowseNodeAttributesResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetProductsBrowseNodeAttributesResponse.  # noqa: E501
        :type data: List[GetProductsBrowseNodeAttributesResponseData]
        """
        self.swagger_types = {
            'message': str,
            'data': List[GetProductsBrowseNodeAttributesResponseData]
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetProductsBrowseNodeAttributesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProductsBrowseNodeAttributesResponse of this GetProductsBrowseNodeAttributesResponse.  # noqa: E501
        :rtype: GetProductsBrowseNodeAttributesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetProductsBrowseNodeAttributesResponse.


        :return: The message of this GetProductsBrowseNodeAttributesResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetProductsBrowseNodeAttributesResponse.


        :param message: The message of this GetProductsBrowseNodeAttributesResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> List[GetProductsBrowseNodeAttributesResponseData]:
        """Gets the data of this GetProductsBrowseNodeAttributesResponse.


        :return: The data of this GetProductsBrowseNodeAttributesResponse.
        :rtype: List[GetProductsBrowseNodeAttributesResponseData]
        """
        return self._data

    @data.setter
    def data(self, data: List[GetProductsBrowseNodeAttributesResponseData]):
        """Sets the data of this GetProductsBrowseNodeAttributesResponse.


        :param data: The data of this GetProductsBrowseNodeAttributesResponse.
        :type data: List[GetProductsBrowseNodeAttributesResponseData]
        """

        self._data = data
