# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sub_attr import SubAttr  # noqa: F401,E501
from swagger_server.models.title_dic import TitleDic  # noqa: F401,E501
from swagger_server import util


class GetDictionaryBrowseNodesAllResponseSubAttrs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, sub_attr: SubAttr=None, title_dics: List[TitleDic]=None):  # noqa: E501
        """GetDictionaryBrowseNodesAllResponseSubAttrs - a model defined in Swagger

        :param sub_attr: The sub_attr of this GetDictionaryBrowseNodesAllResponseSubAttrs.  # noqa: E501
        :type sub_attr: SubAttr
        :param title_dics: The title_dics of this GetDictionaryBrowseNodesAllResponseSubAttrs.  # noqa: E501
        :type title_dics: List[TitleDic]
        """
        self.swagger_types = {
            'sub_attr': SubAttr,
            'title_dics': List[TitleDic]
        }

        self.attribute_map = {
            'sub_attr': 'sub_attr',
            'title_dics': 'title_dics'
        }

        self._sub_attr = sub_attr
        self._title_dics = title_dics

    @classmethod
    def from_dict(cls, dikt) -> 'GetDictionaryBrowseNodesAllResponseSubAttrs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetDictionaryBrowseNodesAllResponse_sub_attrs of this GetDictionaryBrowseNodesAllResponseSubAttrs.  # noqa: E501
        :rtype: GetDictionaryBrowseNodesAllResponseSubAttrs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sub_attr(self) -> SubAttr:
        """Gets the sub_attr of this GetDictionaryBrowseNodesAllResponseSubAttrs.


        :return: The sub_attr of this GetDictionaryBrowseNodesAllResponseSubAttrs.
        :rtype: SubAttr
        """
        return self._sub_attr

    @sub_attr.setter
    def sub_attr(self, sub_attr: SubAttr):
        """Sets the sub_attr of this GetDictionaryBrowseNodesAllResponseSubAttrs.


        :param sub_attr: The sub_attr of this GetDictionaryBrowseNodesAllResponseSubAttrs.
        :type sub_attr: SubAttr
        """

        self._sub_attr = sub_attr

    @property
    def title_dics(self) -> List[TitleDic]:
        """Gets the title_dics of this GetDictionaryBrowseNodesAllResponseSubAttrs.


        :return: The title_dics of this GetDictionaryBrowseNodesAllResponseSubAttrs.
        :rtype: List[TitleDic]
        """
        return self._title_dics

    @title_dics.setter
    def title_dics(self, title_dics: List[TitleDic]):
        """Sets the title_dics of this GetDictionaryBrowseNodesAllResponseSubAttrs.


        :param title_dics: The title_dics of this GetDictionaryBrowseNodesAllResponseSubAttrs.
        :type title_dics: List[TitleDic]
        """

        self._title_dics = title_dics
