# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_products_browse_node_valid_value_response_data import GetProductsBrowseNodeValidValueResponseData  # noqa: F401,E501
from swagger_server import util


class GetProductsBrowseNodeValidValueResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: GetProductsBrowseNodeValidValueResponseData=None):  # noqa: E501
        """GetProductsBrowseNodeValidValueResponse - a model defined in Swagger

        :param message: The message of this GetProductsBrowseNodeValidValueResponse.  # noqa: E501
        :type message: str
        :param data: The data of this GetProductsBrowseNodeValidValueResponse.  # noqa: E501
        :type data: GetProductsBrowseNodeValidValueResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': GetProductsBrowseNodeValidValueResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'GetProductsBrowseNodeValidValueResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetProductsBrowseNodeValidValueResponse of this GetProductsBrowseNodeValidValueResponse.  # noqa: E501
        :rtype: GetProductsBrowseNodeValidValueResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this GetProductsBrowseNodeValidValueResponse.


        :return: The message of this GetProductsBrowseNodeValidValueResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this GetProductsBrowseNodeValidValueResponse.


        :param message: The message of this GetProductsBrowseNodeValidValueResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> GetProductsBrowseNodeValidValueResponseData:
        """Gets the data of this GetProductsBrowseNodeValidValueResponse.


        :return: The data of this GetProductsBrowseNodeValidValueResponse.
        :rtype: GetProductsBrowseNodeValidValueResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetProductsBrowseNodeValidValueResponseData):
        """Sets the data of this GetProductsBrowseNodeValidValueResponse.


        :param data: The data of this GetProductsBrowseNodeValidValueResponse.
        :type data: GetProductsBrowseNodeValidValueResponseData
        """

        self._data = data
