# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.feed_submission_info import FeedSubmissionInfo  # noqa: F401,E501
from swagger_server import util


class PostSubmitFeedResponseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, feed_submission_info: FeedSubmissionInfo=None):  # noqa: E501
        """PostSubmitFeedResponseData - a model defined in Swagger

        :param feed_submission_info: The feed_submission_info of this PostSubmitFeedResponseData.  # noqa: E501
        :type feed_submission_info: FeedSubmissionInfo
        """
        self.swagger_types = {
            'feed_submission_info': FeedSubmissionInfo
        }

        self.attribute_map = {
            'feed_submission_info': 'feed_submission_info'
        }

        self._feed_submission_info = feed_submission_info

    @classmethod
    def from_dict(cls, dikt) -> 'PostSubmitFeedResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostSubmitFeedResponse_data of this PostSubmitFeedResponseData.  # noqa: E501
        :rtype: PostSubmitFeedResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feed_submission_info(self) -> FeedSubmissionInfo:
        """Gets the feed_submission_info of this PostSubmitFeedResponseData.


        :return: The feed_submission_info of this PostSubmitFeedResponseData.
        :rtype: FeedSubmissionInfo
        """
        return self._feed_submission_info

    @feed_submission_info.setter
    def feed_submission_info(self, feed_submission_info: FeedSubmissionInfo):
        """Sets the feed_submission_info of this PostSubmitFeedResponseData.


        :param feed_submission_info: The feed_submission_info of this PostSubmitFeedResponseData.
        :type feed_submission_info: FeedSubmissionInfo
        """

        self._feed_submission_info = feed_submission_info
