# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.post_submit_feed_response_data import PostSubmitFeedResponseData  # noqa: F401,E501
from swagger_server import util


class PostSubmitFeedResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, message: str=None, data: PostSubmitFeedResponseData=None):  # noqa: E501
        """PostSubmitFeedResponse - a model defined in Swagger

        :param message: The message of this PostSubmitFeedResponse.  # noqa: E501
        :type message: str
        :param data: The data of this PostSubmitFeedResponse.  # noqa: E501
        :type data: PostSubmitFeedResponseData
        """
        self.swagger_types = {
            'message': str,
            'data': PostSubmitFeedResponseData
        }

        self.attribute_map = {
            'message': 'message',
            'data': 'data'
        }

        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'PostSubmitFeedResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PostSubmitFeedResponse of this PostSubmitFeedResponse.  # noqa: E501
        :rtype: PostSubmitFeedResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this PostSubmitFeedResponse.


        :return: The message of this PostSubmitFeedResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this PostSubmitFeedResponse.


        :param message: The message of this PostSubmitFeedResponse.
        :type message: str
        """

        self._message = message

    @property
    def data(self) -> PostSubmitFeedResponseData:
        """Gets the data of this PostSubmitFeedResponse.


        :return: The data of this PostSubmitFeedResponse.
        :rtype: PostSubmitFeedResponseData
        """
        return self._data

    @data.setter
    def data(self, data: PostSubmitFeedResponseData):
        """Sets the data of this PostSubmitFeedResponse.


        :param data: The data of this PostSubmitFeedResponse.
        :type data: PostSubmitFeedResponseData
        """

        self._data = data
