# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TopItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, asin: str=None, title: str=None, detail_page_url: str=None, product_group: str=None):  # noqa: E501
        """TopItem - a model defined in Swagger

        :param asin: The asin of this TopItem.  # noqa: E501
        :type asin: str
        :param title: The title of this TopItem.  # noqa: E501
        :type title: str
        :param detail_page_url: The detail_page_url of this TopItem.  # noqa: E501
        :type detail_page_url: str
        :param product_group: The product_group of this TopItem.  # noqa: E501
        :type product_group: str
        """
        self.swagger_types = {
            'asin': str,
            'title': str,
            'detail_page_url': str,
            'product_group': str
        }

        self.attribute_map = {
            'asin': 'asin',
            'title': 'title',
            'detail_page_url': 'detail_page_url',
            'product_group': 'product_group'
        }

        self._asin = asin
        self._title = title
        self._detail_page_url = detail_page_url
        self._product_group = product_group

    @classmethod
    def from_dict(cls, dikt) -> 'TopItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TopItem of this TopItem.  # noqa: E501
        :rtype: TopItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def asin(self) -> str:
        """Gets the asin of this TopItem.


        :return: The asin of this TopItem.
        :rtype: str
        """
        return self._asin

    @asin.setter
    def asin(self, asin: str):
        """Sets the asin of this TopItem.


        :param asin: The asin of this TopItem.
        :type asin: str
        """

        self._asin = asin

    @property
    def title(self) -> str:
        """Gets the title of this TopItem.


        :return: The title of this TopItem.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this TopItem.


        :param title: The title of this TopItem.
        :type title: str
        """

        self._title = title

    @property
    def detail_page_url(self) -> str:
        """Gets the detail_page_url of this TopItem.


        :return: The detail_page_url of this TopItem.
        :rtype: str
        """
        return self._detail_page_url

    @detail_page_url.setter
    def detail_page_url(self, detail_page_url: str):
        """Sets the detail_page_url of this TopItem.


        :param detail_page_url: The detail_page_url of this TopItem.
        :type detail_page_url: str
        """

        self._detail_page_url = detail_page_url

    @property
    def product_group(self) -> str:
        """Gets the product_group of this TopItem.


        :return: The product_group of this TopItem.
        :rtype: str
        """
        return self._product_group

    @product_group.setter
    def product_group(self, product_group: str):
        """Sets the product_group of this TopItem.


        :param product_group: The product_group of this TopItem.
        :type product_group: str
        """

        self._product_group = product_group
